<?php
echo "<h1 style='text-align:center'>";
echo "项目说明";
echo "</h1>";
echo "<h3 style='left: 30%'>";
echo "登陆账号：a@a  密码：a";
echo "<br />";
echo "<br />";
echo "后台地址：http://www.weiai.ink/admin ";
echo "<br />";
echo "<br />";
echo "后台账号密码：admin admin";
echo "<br />";
echo "<br />";
echo "商城注册的邮箱没有验证的将不能下单，如需要测试下单请使用提供账号或联系站长激活邮箱";
echo "<br />";
echo "<br />";
echo "本平台的功能有：";
echo "<br />";
echo "<br />";
echo "&nbsp;&nbsp;";
echo "账号注册,邮箱验证，账号登陆,选择商品，加入购物车，提交订单，支付宝支付（沙箱环境）,使用优惠卷，查看订单，订单评价;";
echo "<br />";
echo "<br />";
echo "正在开发的功能：";
echo "<br />&nbsp;&nbsp;";
echo "<br />";
echo "分销模式，分期付款";
echo "<h3/>";